### PR TITLE
CMake OSX compatibility

### PR DESCRIPTION
**Pull request by brainstorm**
Solves the issue outlined in https://github.com/markmaker/TinyG/pull/3#issuecomment-1458064732

Thanks for your patience waiting for almost 1 year after that last message X"D

I hope it doesn't break the build on Linux now, haven't tested :-S

### CODE REVIEW

**Comment by ian-arkver** [comment]
Goodness, it's been a while. I'll try to test this change in the next week to see if it affects Linux compilation. I'd guess it's ok though from a swift eyeball.
Why the 3 commented out sets? Are they ever needed? If not it might be cleaner to remove them to avoid confusion.

**Comment by brainstorm** [comment]
Thanks Ian! 

I can definitely remove those lines. I was experimenting with the minimum amount of flags required for the OSX build to work... I'm not too happy about using that internal CMake variable `_CMAKE_APPLE_ARCHS_DEFAULT` since (I guess) it could go away anytime in the future and the [kitware issue thread](https://gitlab.kitware.com/cmake/cmake/-/issues/24599) seemed to have better alternative suggestions?

How would you tweak those given the aforementioned thread so that there are no brittle private CMake vars?

**Comment by brainstorm** [comment]
It does break on Linux for GCC 13.x, I'll add this: https://github.com/brainstorm/TinyG-openpnp/commit/b99e148ef83a45f4795d414de3ad97ffc4fdb136

Works on Linux now after my recent couple of commits on this PR, tested on:

```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 23.10
Release:        23.10
Codename:       mantic

$ avr-gcc --version
avr-gcc (GCC) 5.4.0
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$ gcc --version
gcc (Ubuntu 13.2.0-4ubuntu3) 13.2.0
Copyright (C) 2023 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$ cmake --version
cmake version 3.27.4
```

**Comment by brainstorm** [comment]
Meow?

**Comment by ian-arkver** [comment]
Sorry, it's been an "interesting" couple of weeks. Tested with avr-gcc 13.2.0 on Linux. Compiles. Merged.

**Pull request merged**
